version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: myprojectpass
     
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles/
    ports:
      - "8000:8000"
    depends_on:
      - db   

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/app/logs
      - static_volume:/app/staticfiles/
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:





